<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<!-- where should the nuget package be created at -->
	<PackageOutputPath>./nupkg</PackageOutputPath>

	<!-- nuget related properties -->
	<Authors>Md Amanul Huque, Md. Khalid Mahmud</Authors>
	<Description>DbManager is a powerful package that simplifies the integration of CRUD.  It seamlessly supports various database systems like MS SQL Server, MySQL</Description>
	<Version>3.0.2</Version>
	<Copyright>Copyright 2024 © Md Amanul Huque. All rights reserved.</Copyright>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
	<RepositoryUrl>https://github.com/ony19161/dbmanager/tree/efcore-dev/dotnet-8</RepositoryUrl>
	<RepositoryType>git</RepositoryType>
	<AssemblyName>DbManager.EFCore</AssemblyName>
	<PackageReadmeFile>README.md</PackageReadmeFile>
	<PackageTags>Db, Context, EFCore, Multiple Provider</PackageTags>
	<PackageReleaseNotes>-Minor refactoring in base repository</PackageReleaseNotes>
	<PackageProjectUrl>https://github.com/ony19161/dbmanager/tree/efcore-dev/dotnet-8</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.11" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.2" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Factories\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
